# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(b'SL', b'Solicitante'), (b'JD', b'Jefe Directo'), (b'A1', b'Aprobador 1'), (b'A2', b'Aprobador 2'), (b'AS', b'Administrador de Solicitudes'), (b'RP', b'Responsable del proceso')], default=b'SL', max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
