# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vacantes', models.PositiveIntegerField(default=1)),
                ('cargo', models.CharField(choices=[('NV', 'Nuevo'), ('RE', 'Reemplazo')], default='NV', max_length=2)),
                ('jornada', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time')], default='FT', max_length=2)),
                ('salario', models.CharField(blank=True, max_length=50, null=True)),
                ('estatus', models.CharField(choices=[(b'SL', b'Solicitante'), (b'JD', b'Jefe Directo'), (b'A1', b'Aprobador 1'), (b'A2', b'Aprobador 2'), (b'AS', b'Administrador de Solicitudes'), (b'RP', b'Responsable del proceso')], default=b'SL', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibido_por', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='estatussolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.SolicitudVacante'),
        ),
        migrations.AddField(
            model_name='estatussolicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
