# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacante',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
