# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 05:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0002_solicitudvacante_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=None)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.SolicitudVacante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='estatussolicitud',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='estatussolicitud',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='EstatusSolicitud',
        ),
    ]
