# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_auto_20170111_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacante',
            name='aprobado',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='revisionsolicitud',
            name='aprobado',
            field=models.NullBooleanField(default=None),
        ),
    ]
