# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_auto_20170111_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudvacante',
            old_name='recibido_por',
            new_name='responsable',
        ),
        migrations.AlterField(
            model_name='revisionsolicitud',
            name='aprobado',
            field=models.NullBooleanField(choices=[(None, '---'), (True, 'Aprobar'), (False, 'Negar')], default=None),
        ),
        migrations.AlterField(
            model_name='solicitudvacante',
            name='estatus',
            field=models.CharField(choices=[(b'SL', b'Solicitante'), (b'JD', b'Jefe Directo'), (b'A1', b'Aprobador 1'), (b'A2', b'Aprobador 2'), (b'AS', b'Administrador de Solicitudes'), (b'RP', b'Responsable del proceso')], default=b'JD', max_length=2, verbose_name='Enviar a'),
        ),
    ]
