# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0005_auto_20170111_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacante',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprobado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudvacante',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
